#!/usr/bin/env python

import argparse

import lava_salt


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=lava_salt.start.__doc__)
    parser.add_argument('instance', metavar='<instance>',
                        help='The instance name to start')
    args = parser.parse_args()

    client = lava_salt.salt_client()
    ret = lava_salt.start(client, args.instance)
    if ret:
        print 'salt started the following instances:'
        print ret
    else:
        print 'Instance already running on all minions'
