#!/usr/bin/env python

import argparse

import lava_salt


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=lava_salt.add_worker.__doc__)
    parser.add_argument('minion', metavar='<minion>',
                        help='The host to install the lava worker instance on.')
    parser.add_argument('ip', metavar='<ip>',
                        help='The public IP address for the minion.')
    parser.add_argument('instance', metavar='<instance>',
                        help='The instance name we are creating on the worker')
    parser.add_argument('--dry-run', dest='dryrun', action='store_true',
                        help='Just display what would be changed')
    args = parser.parse_args()

    client = lava_salt.salt_client()
    ret = lava_salt.add_worker(client, args.minion, args.ip, args.instance, args.dryrun)
    print ret[args.minion]
