#!/usr/bin/env python

import argparse

import lava_salt


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=lava_salt.stop.__doc__)
    parser.add_argument('--just-workers', dest='just_workers', action='store_true',
                        help='Just stop worker instances, not the master')
    parser.add_argument('instance', metavar='<instance>',
                        help='The instance name to stop')
    args = parser.parse_args()

    client = lava_salt.salt_client()
    ret = lava_salt.stop(client, args.instance, args.just_workers)
    if ret:
        print 'salt stopped the following instances:'
        print ret
    else:
        print 'Instance not running on any minions'
