#!/usr/bin/env python

import argparse

import lava_salt


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=lava_salt.info.__doc__)
    parser.add_argument('instance', metavar='<instance>',
                        help='The instance name to stop')
    args = parser.parse_args()

    client = lava_salt.salt_client()

    for host, props in lava_salt.info(client, args.instance).iteritems():
        running = lava_salt.STATE_STRING[props['running']]
        master = props['master']
	dispatcher = props['dispatcher']
	server = props['server']
        print '{0}: running({1}) master({2}) dispatcher-version:({3}) server-version:({4})'.format(host, running, master, dispatcher, server)
