#! /bin/bash
### BEGIN INIT INFO
# Provides: ARM Ltd
# Required-Start: $local_fs $network $syslog
# Should-Start:
# Required-Stop: $local_fs $network $syslog
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: FM Network Setup
# Description: FM Network Setup
#              Create TAP deivces and network bridge for Fast Models
#              See http://www.arm.com/products/tools/fast-models.php
#              for more information.
### END INIT INFO

# This is an example of a Linux LSB conforming init script.
# See http://refspecs.freestandards.org/ for more information on LSB.

# $FastModels$

# source function library
if [ -e /etc/rc.d/init.d/functions ];then
    source /etc/rc.d/init.d/functions
elif [ -e /lib/lsb/init-functions ];then
    source /lib/lsb/init-functions
else
    echo 'Unable to find lsb functions'
fi
PATH=.:/sbin:/usr/sbin:/bin:/usr/bin
user="www-data"
INTERFACES="01 02"
NIC=eth0
PREFIX=armv8_
BRIDGE=br0

function checkCommands(){
    if ! type tapctrl > /dev/null 2>&1; then
        echo "ERROR: Please install the tapctrl command"
        exit 1
    fi
    if ! type brctl > /dev/null 2>&1; then
        echo  "ERROR: Please install the bridge-utils package for brctl command"
        exit 1
    fi
}

start(){
    checkCommands
    ifconfig $NIC promisc
    ifconfig $BRIDGE promisc
    for interface in $INTERFACES; do
       interface_name=$PREFIX$interface
       tapctrl -n ${interface_name} -a create -o $user -t tap
       ifconfig ${interface_name} 0.0.0.0 promisc up
       brctl addif $BRIDGE ${interface_name}
    done
}

stop(){
    checkCommands
    ifconfig $NIC -promisc
    ifconfig $BRIDGE -promisc
    for interface in $INTERFACES; do
       interface_name=$PREFIX$interface
       ifconfig ${interface_name} down
       brctl delif $BRIDGE ${interface_name}
       tapctrl -n ${interface_name} -a delete -o $user -t tap
    done
}
RETVAL=0
case "$1" in
    start)
           start
           ;;
    stop)
           stop
           ;;
    restart)
           stop
           start
           ;;
    *)
           echo -e "Usage: $0 {start|stop|restart}"
           RETVAL=1
esac

exit $RETVAL
# Script End
